### ISSUE TITLE
vertical scrolling

### ISSUE THREAD

**Issue by henposolera** [Vykyan/retroTINK-setup#3]
Hi,
Thanks for the setup. Your default settings create vertical scrolling on my sony CRT, I reduced the number of the <v_active_lines> to 240 and it worked fine. However, I am now experiencing an issue when I want to exit retroarch and go back to emulatestation. Basically, once I go back, the scrolling starts again. 
Any ideas about what setting should I change?

Thanks

**Comment by henposolera** [comment]
Never mind, forgot to update runcommand-onend.sh . It's all good now. Thanks

**Comment by JamesModoLabs** [comment]
@henposolera I am having the same issue, what were the setting you changed?

**Comment by henposolera** [comment]
Hi There,

Try to use the settings from my repo.
https://github.com/henposolera/RetrotinkUpdate
